name: Super-Linter

on: push

jobs:
  super-lint:
    name: lint code base
    runs-on: ubuntu-latest
    steps:
      -name: CHeckout code
      -uses: actions/checkout@v2

      -name: Run Super-linter
      -uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOCKEN: ${{ secrets.GITHUB_TOCKEN }}
